/* Generated by tools/gen_tables.py -- do not edit.
 *
 * TWO Unicode versions are pinned here, and that is not a mistake.  The
 * HuggingFace tokenizers build this library must match token for token uses
 * separate components for regex matching and for normalization, and they
 * carry different bundled Unicode data.  Both pins were established by
 * probing the build itself, not by reading its documentation.
 *
 * Character classes: Unicode 16.0.0.
 *   Taken from the behavioural probe, which is the exactness ground truth:
 *     tests/data/hf_classes.bin.gz
 *     sha256 4cd900fb2d2da04488e26cd027d5276964abc685c7a7c74eed22d8224a8214e7
 *   Cross-checked against the pinned UCD 16.0.0 files:
 *     CompositionExclusions.txt      sha256 89e83cf9cc8bef6c1f8bf77e42cf6f0341dfa42e66261f4dbe9b492e7a23c8ee
 *     DerivedNormalizationProps.txt  sha256 4d4c03892dea9146d674b686e495df2d55a28d071ac474041d73518f887abddc
 *     NormalizationTest.txt          sha256 d811971453e7075e1ad56fb1b301eece5aa80757b81f6156e74a1bfb3ae5ceb1
 *     UnicodeData.txt                sha256 ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f
 *
 * NFC data: Unicode 9.0.0.
 *   The build ships 2016-era normalization data: it treats every combining
 *   mark assigned after 9.0.0 as an unknown starter, and does not compose
 *   decompositions added since.  Emitting newer data here would break
 *   exactness rather than improve it.  Evidence, regenerated by
 *   tools/probe_nfc_version.py and verified at generation time:
 *     tests/data/hf_nfc_probe.json
 *     sha256 76517c31ec734c20f5cad0e23fbf0215dd3ca2c41b7381f5391a15bd17befd96
 *   Taken from the pinned UCD 9.0.0 files:
 *     CompositionExclusions.txt      sha256 5623df16856ad4007c60bdfff6f054e087521becd24cb4006be69c3a1d851aee
 *     DerivedNormalizationProps.txt  sha256 02d8e12cea7c61a9f3cc5fbf8eaceadf8da23fe83d60c64cf647088830b810cc
 *     NormalizationTest.txt          sha256 2d48d848656b3cf889df59980ab13551988950c4ca8c5190a17c691a17f8b9bb
 *     UnicodeData.txt                sha256 68dfc414d28257b9b5d6ddbb8b466c768c00ebdf6cbf7784364a9b6cad55ee8f
 *
 * Regenerate with:
 *   python3 tools/gen_tables.py
 */


#include "bp_uctables.h"

#include <stdio.h>


static int failures;

static void check(const char *what, unsigned long cp, long got, long want)
{
    if (got != want) {
        printf("FAIL %s U+%04lX: got %ld, want %ld\n", what, cp, got, want);
        failures++;
    }
}

struct u32_case { uint32_t cp; uint32_t want; };

static const struct u32_case class_cases[] = {
    { 0x000000u, 0u },
    { 0x000009u, 4u },
    { 0x00000Au, 12u },
    { 0x00000Du, 12u },
    { 0x000020u, 4u },
    { 0x000027u, 0u },
    { 0x000030u, 2u },
    { 0x000041u, 1u },
    { 0x00005Au, 1u },
    { 0x00007Au, 1u },
    { 0x000085u, 4u },
    { 0x0000A0u, 4u },
    { 0x0000B2u, 2u },
    { 0x0000C9u, 1u },
    { 0x000301u, 0u },
    { 0x000660u, 2u },
    { 0x0006F0u, 2u },
    { 0x000F20u, 2u },
    { 0x00180Eu, 0u },
    { 0x001680u, 4u },
    { 0x002000u, 4u },
    { 0x00200Au, 4u },
    { 0x00200Bu, 0u },
    { 0x002028u, 4u },
    { 0x002029u, 4u },
    { 0x00202Fu, 4u },
    { 0x00205Fu, 4u },
    { 0x002160u, 2u },
    { 0x003000u, 4u },
    { 0x003042u, 1u },
    { 0x004E00u, 1u },
    { 0x00AC00u, 1u },
    { 0x00FFFDu, 0u },
    { 0x010000u, 1u },
    { 0x01D7CEu, 2u },
    { 0x01F600u, 0u },
    { 0x0E0001u, 0u },
    { 0x10FFFFu, 0u },
};

static const struct u32_case ccc_cases[] = {
    { 0x000041u, 0u },
    { 0x000300u, 230u },
    { 0x000301u, 230u },
    { 0x000316u, 220u },
    { 0x000334u, 1u },
    { 0x000345u, 240u },
    { 0x0005B0u, 10u },
    { 0x00093Cu, 7u },
    { 0x000E38u, 103u },
    { 0x003099u, 8u },
    { 0x001E00u, 0u },
    { 0x10FFFFu, 0u },
    { 0x000897u, 0u },
    { 0x0007FDu, 0u },
    { 0x0009FEu, 0u },
    { 0x000C3Cu, 0u },
    { 0x001ABFu, 0u },
    { 0x001DF9u, 0u },
    { 0x01E130u, 0u },
    { 0x01193Du, 0u },
    { 0x00089Au, 0u },
    { 0x010EFDu, 0u },
};

static const struct u32_case qc_cases[] = {
    { 0x000041u, 1u },
    { 0x000300u, 2u },
    { 0x000344u, 0u },
    { 0x000958u, 0u },
    { 0x0009DCu, 0u },
    { 0x000F43u, 0u },
    { 0x001E69u, 1u },
    { 0x002126u, 0u },
    { 0x00212Bu, 0u },
    { 0x00FB1Du, 0u },
    { 0x01D160u, 0u },
};

struct decomp_case { uint32_t cp; int n; uint32_t out[4]; };

static const struct decomp_case decomp_cases[] = {
    { 0x000041u, 0, { 0x000000u, 0x000000u, 0x000000u, 0x000000u } },
    { 0x0000C0u, 2, { 0x000041u, 0x000300u, 0x000000u, 0x000000u } },
    { 0x0000C9u, 2, { 0x000045u, 0x000301u, 0x000000u, 0x000000u } },
    { 0x0001D5u, 3, { 0x000055u, 0x000308u, 0x000304u, 0x000000u } },
    { 0x000344u, 2, { 0x000308u, 0x000301u, 0x000000u, 0x000000u } },
    { 0x000958u, 2, { 0x000915u, 0x00093Cu, 0x000000u, 0x000000u } },
    { 0x001E69u, 3, { 0x000073u, 0x000323u, 0x000307u, 0x000000u } },
    { 0x001F82u, 4, { 0x0003B1u, 0x000313u, 0x000300u, 0x000345u } },
    { 0x002126u, 1, { 0x0003A9u, 0x000000u, 0x000000u, 0x000000u } },
    { 0x00212Bu, 2, { 0x000041u, 0x00030Au, 0x000000u, 0x000000u } },
    { 0x002ADCu, 2, { 0x002ADDu, 0x000338u, 0x000000u, 0x000000u } },
    { 0x00AC00u, 0, { 0x000000u, 0x000000u, 0x000000u, 0x000000u } },
    { 0x00D7A3u, 0, { 0x000000u, 0x000000u, 0x000000u, 0x000000u } },
    { 0x01109Au, 2, { 0x011099u, 0x0110BAu, 0x000000u, 0x000000u } },
    { 0x0105C9u, 0, { 0x000000u, 0x000000u, 0x000000u, 0x000000u } },
    { 0x011383u, 0, { 0x000000u, 0x000000u, 0x000000u, 0x000000u } },
    { 0x0113C5u, 0, { 0x000000u, 0x000000u, 0x000000u, 0x000000u } },
    { 0x011938u, 0, { 0x000000u, 0x000000u, 0x000000u, 0x000000u } },
    { 0x016121u, 0, { 0x000000u, 0x000000u, 0x000000u, 0x000000u } },
    { 0x016D68u, 0, { 0x000000u, 0x000000u, 0x000000u, 0x000000u } },
};

struct compose_case { uint32_t a, b, want; };

static const struct compose_case compose_cases[] = {
    { 0x000041u, 0x000301u, 0x0000C1u },
    { 0x000045u, 0x000301u, 0x0000C9u },
    { 0x000041u, 0x00030Au, 0x0000C5u },
    { 0x000043u, 0x000327u, 0x0000C7u },
    { 0x000055u, 0x000308u, 0x0000DCu },
    { 0x000928u, 0x00093Cu, 0x000929u },
    { 0x000915u, 0x00093Cu, 0x000000u },
    { 0x001100u, 0x001161u, 0x000000u },
    { 0x00AC00u, 0x0011A8u, 0x000000u },
    { 0x000041u, 0x000041u, 0x000000u },
    { 0x000000u, 0x000000u, 0x000000u },
    { 0x0003A9u, 0x000301u, 0x00038Fu },
    { 0x000073u, 0x000323u, 0x001E63u },
    { 0x001E63u, 0x000307u, 0x001E69u },
    { 0x011935u, 0x011930u, 0x000000u },
    { 0x0113C2u, 0x0113C2u, 0x000000u },
    { 0x01611Eu, 0x01611Eu, 0x000000u },
    { 0x016D67u, 0x016D67u, 0x000000u },
    { 0x0105D2u, 0x000307u, 0x000000u },
};


int main(void)
{
    size_t i, j;
    uint32_t out[4];
    int n;

    for (i = 0; i < sizeof class_cases / sizeof class_cases[0]; i++) {
        check("class", class_cases[i].cp,
              bp_char_class(class_cases[i].cp), (long)class_cases[i].want);
    }
    check("class", 0x110000ul, bp_char_class(0x110000u), 0);
    check("class", 0xFFFFFFFFul, bp_char_class(0xFFFFFFFFu), 0);

    for (i = 0; i < sizeof ccc_cases / sizeof ccc_cases[0]; i++) {
        check("ccc", ccc_cases[i].cp, bp_ccc(ccc_cases[i].cp), (long)ccc_cases[i].want);
    }
    check("ccc", 0x110000ul, bp_ccc(0x110000u), 0);

    for (i = 0; i < sizeof qc_cases / sizeof qc_cases[0]; i++) {
        check("nfc_qc", qc_cases[i].cp,
              bp_nfc_qc(qc_cases[i].cp), (long)qc_cases[i].want);
    }

    for (i = 0; i < sizeof decomp_cases / sizeof decomp_cases[0]; i++) {
        n = bp_decomp(decomp_cases[i].cp, out);
        check("decomp count", decomp_cases[i].cp, n, decomp_cases[i].n);
        if (n == decomp_cases[i].n) {
            for (j = 0; j < (size_t)n; j++) {
                check("decomp element", decomp_cases[i].cp,
                      (long)out[j], (long)decomp_cases[i].out[j]);
            }
        }
    }

    for (i = 0; i < sizeof compose_cases / sizeof compose_cases[0]; i++) {
        check("compose", ((unsigned long)compose_cases[i].a << 16)
              | compose_cases[i].b,
              (long)bp_compose(compose_cases[i].a, compose_cases[i].b),
              (long)compose_cases[i].want);
    }

    if (failures != 0) {
        printf("%d failure(s)\n", failures);
        return 1;
    }
    printf("bp_uctables self-test passed (classes UCD " BP_UCD_VERSION
           ", NFC UCD " BP_UCD_NFC_VERSION ")\n");
    return 0;
}
