/* Generated by tools/gen_tables.py -- do not edit.
 *
 * TWO Unicode versions are pinned here, and that is not a mistake.  The
 * HuggingFace tokenizers build this library must match token for token uses
 * separate components for regex matching and for normalization, and they
 * carry different bundled Unicode data.  Both pins were established by
 * probing the build itself, not by reading its documentation.
 *
 * Character classes: Unicode 16.0.0.
 *   Taken from the behavioural probe, which is the exactness ground truth:
 *     tests/data/hf_classes.bin.gz
 *     sha256 4cd900fb2d2da04488e26cd027d5276964abc685c7a7c74eed22d8224a8214e7
 *   Cross-checked against the pinned UCD 16.0.0 files:
 *     CompositionExclusions.txt      sha256 89e83cf9cc8bef6c1f8bf77e42cf6f0341dfa42e66261f4dbe9b492e7a23c8ee
 *     DerivedNormalizationProps.txt  sha256 4d4c03892dea9146d674b686e495df2d55a28d071ac474041d73518f887abddc
 *     NormalizationTest.txt          sha256 d811971453e7075e1ad56fb1b301eece5aa80757b81f6156e74a1bfb3ae5ceb1
 *     UnicodeData.txt                sha256 ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f
 *
 * NFC data: Unicode 9.0.0.
 *   The build ships 2016-era normalization data: it treats every combining
 *   mark assigned after 9.0.0 as an unknown starter, and does not compose
 *   decompositions added since.  Emitting newer data here would break
 *   exactness rather than improve it.  Evidence, regenerated by
 *   tools/probe_nfc_version.py and verified at generation time:
 *     tests/data/hf_nfc_probe.json
 *     sha256 76517c31ec734c20f5cad0e23fbf0215dd3ca2c41b7381f5391a15bd17befd96
 *   Taken from the pinned UCD 9.0.0 files:
 *     CompositionExclusions.txt      sha256 5623df16856ad4007c60bdfff6f054e087521becd24cb4006be69c3a1d851aee
 *     DerivedNormalizationProps.txt  sha256 02d8e12cea7c61a9f3cc5fbf8eaceadf8da23fe83d60c64cf647088830b810cc
 *     NormalizationTest.txt          sha256 2d48d848656b3cf889df59980ab13551988950c4ca8c5190a17c691a17f8b9bb
 *     UnicodeData.txt                sha256 68dfc414d28257b9b5d6ddbb8b466c768c00ebdf6cbf7784364a9b6cad55ee8f
 *
 * Regenerate with:
 *   python3 tools/gen_tables.py
 */

#ifndef BP_UCTABLES_H
#define BP_UCTABLES_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* The two Unicode versions the target build implements.  BP_UCD_VERSION governs the
   character classes; the normalization functions below follow the older
   BP_UCD_NFC_VERSION, because that is what the build does.  See the banner above. */
#define BP_UCD_VERSION "16.0.0"
#define BP_UCD_NFC_VERSION "9.0.0"

/* Character classes of the Qwen3 split regex.  BP_CC_NL is set only for U+000D and
   U+000A, and always together with BP_CC_S. */
enum { BP_CC_L = 1, BP_CC_N = 2, BP_CC_S = 4, BP_CC_NL = 8 };

/* Two-level lookup: 4352 blocks of 256 codepoints, deduplicated. */
#define BP_CC_BLOCK_COUNT 133
extern const uint16_t bp_cc_index[4352];
extern const uint8_t bp_cc_blocks[34048];

/* Class bits of a codepoint; 0 for unclassified and for anything above U+10FFFF. */
static inline uint8_t bp_char_class(uint32_t cp)
{
    if (cp > 0x10FFFFu) {
        return 0;
    }
    return bp_cc_blocks[((uint32_t)bp_cc_index[cp >> 8] << 8) | (cp & 0xFFu)];
}

/* Canonical combining class per Unicode 9.0.0; 0 for starters, for anything above
   U+10FFFF, and for every mark assigned after 9.0.0 -- see the banner. */
uint8_t bp_ccc(uint32_t cp);

/* NFC quick check: 0 = No, 1 = Yes, 2 = Maybe. */
int bp_nfc_qc(uint32_t cp);

/* Full canonical decomposition, already recursively expanded.  Returns the number of
   codepoints written to out (1..4), or 0 if cp has none.  Hangul syllables are
   excluded: their decomposition is algorithmic and belongs in the normalizer. */
int bp_decomp(uint32_t cp, uint32_t out[4]);

/* Primary composite of the pair (a, b), or 0 if the pair does not compose.  Hangul
   jamo composition is excluded and likewise belongs in the normalizer. */
uint32_t bp_compose(uint32_t a, uint32_t b);

#ifdef __cplusplus
}
#endif

#endif /* BP_UCTABLES_H */
